name: EBPF-CI
on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
    branches:
      - Alpha
  pull_request:
    branches:
      - Alpha

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOTOOLCHAIN: auto
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-download-base-url: 'https://github.com/MetaCubeX/go/releases/download/build'
        go-version: '1.26'
    - run: sudo apt-get update && sudo apt-get install -y clang libbpf-dev
    - run: make ebpf CLANG=clang
    - run: go build -v -trimpath -ldflags "-w -s -buildid=" -tags "with_gvisor"
    - run: go test ./... -count=1

  build-darwin:
    runs-on: ubuntu-latest
    env:
      GOOS: darwin
      GOARCH: amd64
      CGO_ENABLED: 0
      GOTOOLCHAIN: auto
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-download-base-url: 'https://github.com/MetaCubeX/go/releases/download/build'
        go-version: '1.26'
    - run: go build -v -trimpath -ldflags "-w -s -buildid="

  build-windows:
    runs-on: ubuntu-latest
    env:
      GOOS: windows
      GOARCH: amd64
      CGO_ENABLED: 0
      GOTOOLCHAIN: auto
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-download-base-url: 'https://github.com/MetaCubeX/go/releases/download/build'
        go-version: '1.26'
    - run: go build -v -trimpath -ldflags "-w -s -buildid="
